function plotrates(p,rates)

m = p.m;
semilogx(m, rates.JF./m, 'r-',...
    m, rates.JL./m, 'g-',...
    m, rates.JN./m, 'b-', ...
    m, rates.Jtot./m, 'k-', ...
    m, rates.JDOC./m, 'm-', ...
    m, -rates.mortpred, 'r-',...
    m, -rates.JR./m,'m-', 'linewidth',3)
hold on
semilogx(m, p.Jmax./m, 'k:')
semilogx(m, 0*m, 'k--')
