function setParameters(p)

if ~libisloaded("model")
    loadlibrary('../Cpp/model.so','../Cpp/model.h')
end

calllib('model','setParameters', ...
    int32(p.n), ...
    double(p.m), ...
    double(p.rhoCN), ...
    double(p.epsilonL), ...
    double(p.epsilonF), ...
    double(p.ANm), ...
    double(p.ALm), ...
    double(p.AFm), ...
    double(p.Jmax), ...
    double(p.JFmaxm), ...
    double(p.Jresp), ...
    double(p.Jloss_passive_m), ...
    p.theta, ...
    double(p.mort), ...
    double(p.mort2), ...
    double(p.mortHTL*p.mortHTLm), ...
    double(p.remin), ...
    double(p.remin2), ...
    double(p.cLeakage))