%
% Simulate one system with Euler-integration:
%
function sim = simulateEuler(p, y, dt, tEnd)
%%
% Load library:
%
if ~libisloaded("model")
    loadlibrary('../Cpp/model.so','../Cpp/model.h');
end
%
% Set parameters:
%
calllib('model','setParameters', ...
    int32(p.n), ...
    double(p.m), ...
    double(p.rhoCN), ...
    double(p.epsilonL), ...
    double(p.epsilonF), ...
    double(p.ANm), ...
    double(p.ALm), ...
    double(p.AFm), ...
    double(p.Jmax), ...
    double(p.JFmaxm), ...
    double(p.Jresp), ...
    double(p.Jloss_passive_m), ...
    p.theta, ...
    double(p.mort), ...
    double(p.mort2), ...
    double(p.mortHTL*p.mortHTLm), ...
    double(p.remin), ...
    double(p.remin2), ...
    double(p.cLeakage))
%%
% Simulate:
%

dydt = 0*y;
y = calllib('model','simulateEuler', y, dydt, ...
    double(p.L), double(p.T), double(dt), double(tEnd));

%%
% Extract result:
%
sim.t = tEnd;
sim.p = p;

sim.Ntime = y(1);
sim.DOCtime = y(2);
sim.Btime = y(3:(2+p.n));

%sim.Bmean = mean(sim.Btime(ixTime,:));
%sim.Nmean = mean(sim.Ntime(ixTime,:));
%sim.DOCmean = mean(sim.DOCtime(ixTime,:));

end
